### ISSUE TITLE
Isn't FroniusSolarApi.Net subfolder incomplete?

### ISSUE THREAD

**Issue by reye** [msiggi/Fronius-Inverter-Solar-Api#1]
Isn't the FroniusSolarApi.Net subfolder incomplete? It only contains the Properties subfolder, at present.

**Comment by JohnKH** [comment]
Yes I just downloaded this for the first time and noticed that. 

I found that installing the nuget package works. Just add the package and change the IP address to suit your inverter and run the testConsole :).

**Comment by msiggi** [comment]
Better late than never! Sorry...
